### ISSUE TITLE
Setup uptime monitoring

### ISSUE THREAD

**Issue by pkoch** [tau-prolog/www.tau-prolog.org#5]
Some Pingdom, or Apex, or something. There's a bunch. Maybe there's something that automatically created GH issues, even?

**Comment by jariazavalverde** [comment]
Hi @pkoch 

Thank you very much for your report and your offer. As I mentioned in #1, currently we use a basic web hosting service, not a dedicated server, so when the page is down it is for some problem with the hosting company.

Usually the problem is solved in a few hours. The only thing I can do is report to the technical support that the webpage doesn't work, but it is like doing nothing. :confused:

**Comment by pkoch** [comment]
I see. I understand how the lack of control over the solution makes this much less appealing.

Perhaps we should consider alternatives? This website seems mostly static, so perhaps porting this to something that can be deployed to a Netlify/Zeit/Surge/etc would make everyone's life easier?

I don't have enough skills and energy to invest in that right now, but perhaps this is a useful challenge for someone. Would you be open to accept contributions in that direction?

**Comment by pkoch** [comment]
Feeling this is stale, closing the issue.

@jariazavalverde Maybe you wanna look at https://github.com/upptime/upptime?
